name: ${project.name}
authors: [Lucariatias, sbliven]
version: ${project.version}
description: ${project.description}
main: io.github.lucariatias.bukkitpopulators.BukkitPopulators
load: STARTUP
softdepend: [SkylandsPlus]